# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
    volumes:
      - ./utils/storage-docker:/var/lib/mysql
    ports:
      - 3306:3306
    secrets:
      - db_root_password

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

secrets:
  db_root_password:
    file: ./db_password.txt
